/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.ClientController;
import forme.evidencija.PrikazEvidencijeForma;
import forme.sertifikat.UbaciSertifikatForma;
import forme.ucenik.PrikazUcenikForma;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Una
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();

        jLabelImeProfesor.setText(ClientController.getInstance().getUlogovani().getIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelImeProfesor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEvidencija = new javax.swing.JMenu();
        jMenuItemPrikaziEvidenciju = new javax.swing.JMenuItem();
        jMenuUcenik = new javax.swing.JMenu();
        jMenuItemPrikaziUcenik = new javax.swing.JMenuItem();
        jMenuSertifikat = new javax.swing.JMenu();
        jMenuItemUbaciSertifikat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Dobrodosli, ");

        jLabelImeProfesor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelImeProfesor.setText("jLabel2");

        jMenuEvidencija.setText("Evidencija casova");

        jMenuItemPrikaziEvidenciju.setText("Prikazi");
        jMenuItemPrikaziEvidenciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziEvidencijuActionPerformed(evt);
            }
        });
        jMenuEvidencija.add(jMenuItemPrikaziEvidenciju);

        jMenuBar1.add(jMenuEvidencija);

        jMenuUcenik.setText("Ucenik");

        jMenuItemPrikaziUcenik.setText("Prikazi");
        jMenuItemPrikaziUcenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziUcenikActionPerformed(evt);
            }
        });
        jMenuUcenik.add(jMenuItemPrikaziUcenik);

        jMenuBar1.add(jMenuUcenik);

        jMenuSertifikat.setText("Sertifikat");

        jMenuItemUbaciSertifikat.setText("Ubaci");
        jMenuItemUbaciSertifikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUbaciSertifikatActionPerformed(evt);
            }
        });
        jMenuSertifikat.add(jMenuItemUbaciSertifikat);

        jMenuBar1.add(jMenuSertifikat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImeProfesor)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelImeProfesor))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPrikaziEvidencijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziEvidencijuActionPerformed
        PrikazEvidencijeForma pef = new PrikazEvidencijeForma();
        pef.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrikaziEvidencijuActionPerformed

    private void jMenuItemPrikaziUcenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziUcenikActionPerformed
        PrikazUcenikForma puf = new PrikazUcenikForma();
        puf.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrikaziUcenikActionPerformed

    private void jMenuItemUbaciSertifikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUbaciSertifikatActionPerformed
        UbaciSertifikatForma usf = new UbaciSertifikatForma();
        usf.setVisible(true);
    }//GEN-LAST:event_jMenuItemUbaciSertifikatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImeProfesor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEvidencija;
    private javax.swing.JMenuItem jMenuItemPrikaziEvidenciju;
    private javax.swing.JMenuItem jMenuItemPrikaziUcenik;
    private javax.swing.JMenuItem jMenuItemUbaciSertifikat;
    private javax.swing.JMenu jMenuSertifikat;
    private javax.swing.JMenu jMenuUcenik;
    // End of variables declaration//GEN-END:variables

}
