/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.ucenik;

import controller.ClientController;
import domen.PlesniNivo;
import domen.Ucenik;
import forme.ModForme;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Una
 */
public class DodajPromeniUcenikForma extends javax.swing.JFrame {

    private PrikazUcenikForma puf;
    private Ucenik u;
    private ModForme mf;

    /**
     * Creates new form DodajPromeniUcenikForma
     */
    public DodajPromeniUcenikForma(PrikazUcenikForma forma, Ucenik ucenik, ModForme mf) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.puf = forma;
        this.u = ucenik;
        this.mf = mf;
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldTelefon = new javax.swing.JTextField();
        jComboBoxPlesniNivo = new javax.swing.JComboBox<>();
        jButtonOdustani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonDogadjaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Broj telefona:");

        jLabel5.setText("Plesni nivo:");

        jComboBoxPlesniNivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPlesniNivo.setToolTipText("");

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime:");

        jButtonDogadjaj.setText("Sacuvaj");
        jButtonDogadjaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDogadjajActionPerformed(evt);
            }
        });

        jLabel2.setText("Prezime:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonOdustani, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jButtonDogadjaj, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxPlesniNivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldIme)
                                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxPlesniNivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOdustani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDogadjaj, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonDogadjajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDogadjajActionPerformed
        try {
            if (mf == ModForme.OBRISI) {
                ClientController.getInstance().obrisiUcenik(u);
                JOptionPane.showMessageDialog(this, "Sistem je obrisao ucenika!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
                puf.prepareView();
                this.dispose();
                return;
            }

            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            String brojTelefona = jTextFieldTelefon.getText().trim();
            PlesniNivo pn = (PlesniNivo) jComboBoxPlesniNivo.getSelectedItem();

            validiraj(ime, prezime, brojTelefona, pn);

            if (mf == ModForme.DODAJ) {
                Ucenik ucenik = new Ucenik(null, ime, prezime, brojTelefona, pn);
                ClientController.getInstance().ubaciUcenik(ucenik);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio ucenika!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            } else if (mf == ModForme.IZMENI) {
                u.setIme(ime);
                u.setPrezime(prezime);
                u.setBrojTelefona(brojTelefona);
                u.setPlesniNivo(pn);
                ClientController.getInstance().promeniUcenik(u);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio ucenika!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            }

            puf.prepareView();
            this.dispose();
        } catch (Exception ex) {
            if (mf == ModForme.OBRISI) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise ucenika!", "Greska!", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti ucenika!", "Greska!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonDogadjajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDogadjaj;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JComboBox<Object> jComboBoxPlesniNivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            jComboBoxPlesniNivo.removeAllItems();
            List<PlesniNivo> plesniNivoi = ClientController.getInstance().vratiListuPlesniNivo();
            for (PlesniNivo pn : plesniNivoi) {
                jComboBoxPlesniNivo.addItem(pn);
            }
            jComboBoxPlesniNivo.setSelectedIndex(-1);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }

        podesiMod();
    }

    private void validiraj(String ime, String prezime, String brojTelefona, PlesniNivo pn) throws Exception {
        String error = "";

        if (ime.isEmpty()) {
            error += "Polje ime ne moze biti prazno!\n";
        }
        if (prezime.isEmpty()) {
            error += "Polje prezime ne moze biti prazno!\n";
        }
        if (brojTelefona.isEmpty()) {
            error += "Polje broj telefona ne moze biti prazno!\n";
        }
        if (pn == null) {
            error += "Morate izabrati plesni nivo!\n";
        }

        if (!error.isEmpty()) {
            throw new Exception(error);
        }
    }

    private void popuniUcenika() {
        jTextFieldIme.setText(u.getIme());
        jTextFieldPrezime.setText(u.getPrezime());
        jTextFieldTelefon.setText(u.getBrojTelefona());
        jComboBoxPlesniNivo.setSelectedItem(u.getPlesniNivo());
    }

    private void podesiMod() {
        if (mf == ModForme.DODAJ) {
            this.setTitle("Dodavanje ucenika");
        } else if (mf == ModForme.IZMENI) {
            popuniUcenika();
            this.setTitle("Promena ucenika");
        } else if (mf == ModForme.OBRISI) {
            popuniUcenika();
            jTextFieldIme.setEditable(false);
            jTextFieldPrezime.setEditable(false);
            jTextFieldTelefon.setEditable(false);
            jComboBoxPlesniNivo.setEnabled(false);
            jButtonDogadjaj.setText("Obrisi");
            this.setTitle("Brisanje ucenika");
        } else if (mf == ModForme.DETALJAN_PRIKAZ) {
            popuniUcenika();
            jTextFieldIme.setEditable(false);
            jTextFieldPrezime.setEditable(false);
            jTextFieldTelefon.setEditable(false);
            jComboBoxPlesniNivo.setEnabled(false);
            jButtonDogadjaj.setVisible(false);
            jButtonOdustani.setText("Nazad");
            this.setTitle("Prikaz ucenika");
        }
    }
}
