/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.ucenik;

import controller.ClientController;
import domen.PlesniNivo;
import domen.Ucenik;
import forme.ModForme;
import java.util.List;
import javax.swing.JOptionPane;
import modeli.ModelTabeleUcenik;

/**
 *
 * @author Una
 */
public class PrikazUcenikForma extends javax.swing.JFrame {

    /**
     * Creates new form PrikazUcenikForma
     */
    public PrikazUcenikForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUcenici = new javax.swing.JTable();
        jButtonPromeniUcenika = new javax.swing.JButton();
        jButtonObrisiUcenika = new javax.swing.JButton();
        jButtonUbacijNovogUcenika = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jComboBoxPlesniNivo = new javax.swing.JComboBox<>();
        jButtonPrikaziSve = new javax.swing.JButton();
        jButtonkreirajDetaljiUcenika = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTableUcenici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUcenici);

        jButtonPromeniUcenika.setText("Promeni ucenika");
        jButtonPromeniUcenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniUcenikaActionPerformed(evt);
            }
        });

        jButtonObrisiUcenika.setText("Obrisi ucenika");
        jButtonObrisiUcenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiUcenikaActionPerformed(evt);
            }
        });

        jButtonUbacijNovogUcenika.setText("Ubaci novog ucenika");
        jButtonUbacijNovogUcenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbacijNovogUcenikaActionPerformed(evt);
            }
        });

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o uceniku:"));
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel5.setText("Plesni nivo:");

        jComboBoxPlesniNivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPlesniNivo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jTextFieldIme))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxPlesniNivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonPrikaziSve.setText("Prikazi sve");
        jButtonPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSveActionPerformed(evt);
            }
        });

        jButtonkreirajDetaljiUcenika.setText("Detalji ucenika");
        jButtonkreirajDetaljiUcenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonkreirajDetaljiUcenikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonPrikaziSve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonkreirajDetaljiUcenika, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonUbacijNovogUcenika, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPromeniUcenika, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonObrisiUcenika, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPrikaziSve, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUbacijNovogUcenika)
                    .addComponent(jButtonPromeniUcenika)
                    .addComponent(jButtonObrisiUcenika)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonkreirajDetaljiUcenika))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            PlesniNivo pn = (PlesniNivo) jComboBoxPlesniNivo.getSelectedItem();

            Ucenik u = new Ucenik();
            u.setIme(ime);
            u.setPrezime(prezime);
            u.setPlesniNivo(pn);

            List<Ucenik> ucenici = ClientController.getInstance().pretraziUcenik(u);

            ModelTabeleUcenik mtu = new ModelTabeleUcenik(ucenici);
            jTableUcenici.setModel(mtu);

            JOptionPane.showMessageDialog(this, "Sistem je nasao ucenike po zadatim kriterijumima!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonPromeniUcenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniUcenikaActionPerformed
        int selektovaniRed = jTableUcenici.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Ucenik za izmenu nije odabran!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleUcenik mtu = (ModelTabeleUcenik) jTableUcenici.getModel();
        Ucenik u = mtu.getUcenici().get(selektovaniRed);
        try {
            Ucenik ucenik = ClientController.getInstance().vratiUcenik(u);
            DodajPromeniUcenikForma dpuf = new DodajPromeniUcenikForma(this, ucenik, ModForme.IZMENI);
            JOptionPane.showMessageDialog(this, "Sistem je nasao ucenika!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            dpuf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPromeniUcenikaActionPerformed

    private void jButtonObrisiUcenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiUcenikaActionPerformed
        int selektovaniRed = jTableUcenici.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Ucenik za brisanje nije odabran!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleUcenik mtu = (ModelTabeleUcenik) jTableUcenici.getModel();
        Ucenik u = mtu.getUcenici().get(selektovaniRed);
        try {
            Ucenik ucenik = ClientController.getInstance().vratiUcenik(u);
            DodajPromeniUcenikForma dpuf = new DodajPromeniUcenikForma(this, ucenik, ModForme.OBRISI);
            JOptionPane.showMessageDialog(this, "Sistem je nasao ucenika!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            dpuf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonObrisiUcenikaActionPerformed

    private void jButtonUbacijNovogUcenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbacijNovogUcenikaActionPerformed
        DodajPromeniUcenikForma dpuf = new DodajPromeniUcenikForma(this, null, ModForme.DODAJ);
        dpuf.setVisible(true);
    }//GEN-LAST:event_jButtonUbacijNovogUcenikaActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSveActionPerformed
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        jComboBoxPlesniNivo.setSelectedIndex(-1);
        popuniTabelu();
    }//GEN-LAST:event_jButtonPrikaziSveActionPerformed

    private void jButtonkreirajDetaljiUcenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonkreirajDetaljiUcenikaActionPerformed
        int selektovaniRed = jTableUcenici.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Ucenik nije odabran!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleUcenik mtu = (ModelTabeleUcenik) jTableUcenici.getModel();
        Ucenik u = mtu.getUcenici().get(selektovaniRed);
        try {
            Ucenik ucenik = ClientController.getInstance().vratiUcenik(u);
            DodajPromeniUcenikForma dpuf = new DodajPromeniUcenikForma(this, ucenik, ModForme.DETALJAN_PRIKAZ);
            JOptionPane.showMessageDialog(this, "Sistem je nasao ucenika!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            dpuf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonkreirajDetaljiUcenikaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisiUcenika;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JButton jButtonPromeniUcenika;
    private javax.swing.JButton jButtonUbacijNovogUcenika;
    private javax.swing.JButton jButtonkreirajDetaljiUcenika;
    private javax.swing.JComboBox<Object> jComboBoxPlesniNivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUcenici;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    public void prepareView() {
        try {
            jComboBoxPlesniNivo.removeAllItems();
            List<PlesniNivo> plesniNivoi = ClientController.getInstance().vratiListuPlesniNivo();
            for (PlesniNivo pn : plesniNivoi) {
                jComboBoxPlesniNivo.addItem(pn);
            }
            jComboBoxPlesniNivo.setSelectedIndex(-1);
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }

        popuniTabelu();
    }

    private void popuniTabelu() {
        try {
            List<Ucenik> ucenici = ClientController.getInstance().vratiListuSviUcenik();
            ModelTabeleUcenik mtu = new ModelTabeleUcenik(ucenici);
            jTableUcenici.setModel(mtu);
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }
}
