/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.evidencija;

import controller.ClientController;
import domen.EvidencijaCasova;
import domen.Profesor;
import domen.Ucenik;
import java.util.List;
import javax.swing.JOptionPane;
import modeli.ModelTabeleEvidencijaCasova;

/**
 *
 * @author Una
 */
public class PrikazEvidencijeForma extends javax.swing.JFrame {

    /**
     * Creates new form PrikazEvidencijeForma
     */
    public PrikazEvidencijeForma() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEvidencija = new javax.swing.JTable();
        jButtonDetaljiEvidencije = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonPromeniEvidenciju = new javax.swing.JButton();
        jTextFieldSkolskaGodina = new javax.swing.JTextField();
        jButtonKreirajEvidenciju = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxProfesor = new javax.swing.JComboBox<>();
        jComboBoxUcenik = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonPrikaziSve = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableEvidencija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEvidencija);

        jButtonDetaljiEvidencije.setText("Detalji evidencije casova");
        jButtonDetaljiEvidencije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiEvidencijeActionPerformed(evt);
            }
        });

        jLabel3.setText("Skolska godina (npr. 2023/2024):");

        jButtonPromeniEvidenciju.setText("Promeni evidenciju");
        jButtonPromeniEvidenciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniEvidencijuActionPerformed(evt);
            }
        });

        jButtonKreirajEvidenciju.setText("Ubaci novu evidenciju");
        jButtonKreirajEvidenciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajEvidencijuActionPerformed(evt);
            }
        });

        jLabel1.setText("Profesor:");

        jComboBoxProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxUcenik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Ucenik:");

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonPrikaziSve.setText("Prikazi sve");
        jButtonPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSveActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDetaljiEvidencije)
                        .addGap(97, 97, 97)
                        .addComponent(jButtonKreirajEvidenciju)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPromeniEvidenciju)
                        .addGap(129, 129, 129)
                        .addComponent(jButtonOdustani)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldSkolskaGodina)
                    .addComponent(jComboBoxProfesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxUcenik, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrikaziSve))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUcenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonPrikaziSve))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSkolskaGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPromeniEvidenciju)
                    .addComponent(jButtonKreirajEvidenciju)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonDetaljiEvidencije))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetaljiEvidencijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiEvidencijeActionPerformed
        int selektovaniRed = jTableEvidencija.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Evidencija casova nije odabrana!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleEvidencijaCasova mte = (ModelTabeleEvidencijaCasova) jTableEvidencija.getModel();
        EvidencijaCasova e = mte.getEvidencije().get(selektovaniRed);
        try {
            EvidencijaCasova evidencija = ClientController.getInstance().vratiEvidencijaCasova(e);
            JOptionPane.showMessageDialog(this, "Sistem je nasao evidenciju casova!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            DetaljiEvidencijeForma def = new DetaljiEvidencijeForma(evidencija);
            def.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDetaljiEvidencijeActionPerformed

    private void jButtonPromeniEvidencijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniEvidencijuActionPerformed
        int selektovaniRed = jTableEvidencija.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Evidencija casova za promenu nije izabrana!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleEvidencijaCasova mte = (ModelTabeleEvidencijaCasova) jTableEvidencija.getModel();
        EvidencijaCasova e = mte.getEvidencije().get(selektovaniRed);
        try {
            EvidencijaCasova evidencija = ClientController.getInstance().vratiEvidencijaCasova(e);
            PromeniEvidencijuForma pef = new PromeniEvidencijuForma(this, evidencija);
            JOptionPane.showMessageDialog(this, "Sistem je pronasao evidenciju casova!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            pef.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPromeniEvidencijuActionPerformed

    private void jButtonKreirajEvidencijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajEvidencijuActionPerformed
        PromeniEvidencijuForma pef = new PromeniEvidencijuForma(this, null);
        pef.setVisible(true);
    }//GEN-LAST:event_jButtonKreirajEvidencijuActionPerformed

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        try {
            Profesor p = (Profesor) jComboBoxProfesor.getSelectedItem();
            Ucenik u = (Ucenik) jComboBoxUcenik.getSelectedItem();
            String skolskaGodina = jTextFieldSkolskaGodina.getText().trim();

            EvidencijaCasova e = new EvidencijaCasova();
            e.setProfesor(p);
            e.setUcenik(u);
            if (!skolskaGodina.isEmpty()) {
                e.setSkolskaGodina(skolskaGodina);
            }

            List<EvidencijaCasova> evidencije = ClientController.getInstance().pretraziEvidencijaCasova(e);
            ModelTabeleEvidencijaCasova mte = new ModelTabeleEvidencijaCasova(evidencije);
            jTableEvidencija.setModel(mte);
            JOptionPane.showMessageDialog(this, "Sistem je nasao evidencije casova po zadatim kriterijumima!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSveActionPerformed
        jComboBoxProfesor.setSelectedIndex(-1);
        jComboBoxUcenik.setSelectedIndex(-1);
        jTextFieldSkolskaGodina.setText("");
        popuniTabelu();
    }//GEN-LAST:event_jButtonPrikaziSveActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetaljiEvidencije;
    private javax.swing.JButton jButtonKreirajEvidenciju;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JButton jButtonPromeniEvidenciju;
    private javax.swing.JComboBox<Object> jComboBoxProfesor;
    private javax.swing.JComboBox<Object> jComboBoxUcenik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEvidencija;
    private javax.swing.JTextField jTextFieldSkolskaGodina;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            jComboBoxProfesor.removeAllItems();
            List<Profesor> profesori = ClientController.getInstance().vratiListuSviProfesor();
            for (Profesor p : profesori) {
                jComboBoxProfesor.addItem(p);
            }
            jComboBoxProfesor.setSelectedIndex(-1);

            jComboBoxUcenik.removeAllItems();
            List<Ucenik> ucenici = ClientController.getInstance().vratiListuSviUcenik();
            for (Ucenik u : ucenici) {
                jComboBoxUcenik.addItem(u);
            }
            jComboBoxUcenik.setSelectedIndex(-1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
        popuniTabelu();
    }

    void popuniTabelu() {
        try {
            List<EvidencijaCasova> evidencije = ClientController.getInstance().vratiListuEvidencijaCasova();
            ModelTabeleEvidencijaCasova mte = new ModelTabeleEvidencijaCasova(evidencije);
            jTableEvidencija.setModel(mte);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }
}
