/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.evidencija;

import controller.ClientController;
import domen.Cas;
import domen.EvidencijaCasova;
import domen.Profesor;
import domen.StavkaEvidencijeCasova;
import domen.Ucenik;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import modeli.ModelTabeleStavkaEvidencijeCasova;

/**
 *
 * @author Una
 */
//validacije ovde omogucavaju da greska bude prikazana klijentu pre nego sto se 
// posalje zahtev serveru
public class PromeniEvidencijuForma extends javax.swing.JFrame {

    private PrikazEvidencijeForma pef;
    private EvidencijaCasova ec;
    private List<StavkaEvidencijeCasova> stavkeEvidencije = new ArrayList<>();

    /**
     * Creates new form PromeniEvidencijuForma
     */
    public PromeniEvidencijuForma(PrikazEvidencijeForma forma, EvidencijaCasova evidencija) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.ec = evidencija;
        this.pef = forma;
        if (ec != null) {
            stavkeEvidencije = ec.getStavke();
        }
        prepareView();
        if (ec != null) {
            popuniPolja();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeEvidencije = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxProfesor = new javax.swing.JComboBox<>();
        jComboBoxUcenik = new javax.swing.JComboBox<>();
        jTextFieldSkolskaGodina = new javax.swing.JTextField();
        jTextFieldDatumPocetka = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDatumZavrsetka = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBrojPrisustva = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTrajanjeEvidencije = new javax.swing.JTextField();
        jTextFieldProsecnaOcena = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonSacuvaj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCasovi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldOcena = new javax.swing.JTextField();
        jButtonDodajStavku = new javax.swing.JButton();
        jButtonObrisiStavku = new javax.swing.JButton();
        jLabelNapomena = new javax.swing.JLabel();
        jTextFieldNapomena = new javax.swing.JTextField();
        jLabelNapomena1 = new javax.swing.JLabel();
        jTextFieldDatumPrisustva = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableStavkeEvidencije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkeEvidencije);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o evidenciji casova:"));

        jLabel1.setText("Profesor:");

        jLabel2.setText("Ucenik:");

        jLabel3.setText("Skolska godina:");

        jLabel4.setText("Datum pocetka:");

        jComboBoxProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxUcenik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Datum zavrsetka:");

        jLabel8.setText("Broj prisustva:");

        jLabel9.setText("Trajanje evidencije:");

        jLabel10.setText("Prosecna ocena:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxProfesor, 0, 255, Short.MAX_VALUE)
                    .addComponent(jComboBoxUcenik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldSkolskaGodina)
                    .addComponent(jTextFieldDatumPocetka)
                    .addComponent(jTextFieldDatumZavrsetka)
                    .addComponent(jTextFieldBrojPrisustva)
                    .addComponent(jTextFieldTrajanjeEvidencije)
                    .addComponent(jTextFieldProsecnaOcena))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxUcenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSkolskaGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldBrojPrisustva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTrajanjeEvidencije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldProsecnaOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke evidencije casova:"));

        jLabel5.setText("Cas:");

        jComboBoxCasovi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Ocena:");

        jButtonDodajStavku.setText("Dodaj stavku");
        jButtonDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStavkuActionPerformed(evt);
            }
        });

        jButtonObrisiStavku.setText("Obrisi stavku");
        jButtonObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiStavkuActionPerformed(evt);
            }
        });

        jLabelNapomena.setText("Napomena:");

        jLabelNapomena1.setText("Datum prisustva:");

        jTextFieldDatumPrisustva.setText("dd.MM.yyyy");
        jTextFieldDatumPrisustva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatumPrisustvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonObrisiStavku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonDodajStavku)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCasovi, 0, 213, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldOcena))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelNapomena)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNapomena))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelNapomena1)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDatumPrisustva))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCasovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOcena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNapomena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatumPrisustva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNapomena1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodajStavku)
                    .addComponent(jButtonObrisiStavku)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSacuvaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        try {
            Profesor profesor = (Profesor) jComboBoxProfesor.getSelectedItem();
            Ucenik ucenik = (Ucenik) jComboBoxUcenik.getSelectedItem();
            String skolskaGodina = jTextFieldSkolskaGodina.getText().trim();
            String datumPocetkaStr = jTextFieldDatumPocetka.getText().trim();
            String datumZavrsetkaStr = jTextFieldDatumZavrsetka.getText().trim();

            validirajEvidenciju(profesor, ucenik, skolskaGodina, datumPocetkaStr, datumZavrsetkaStr);

            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumPocetka = sdf.parse(datumPocetkaStr);
            Date datumZavrsetka = sdf.parse(datumZavrsetkaStr);

            if (ec == null) {
                EvidencijaCasova evidencija = new EvidencijaCasova();
                evidencija.setProfesor(profesor);
                evidencija.setUcenik(ucenik);
                evidencija.setSkolskaGodina(skolskaGodina);
                evidencija.setDatumPocetka(datumPocetka);
                evidencija.setDatumZavrsetka(datumZavrsetka);
                evidencija.setStavke(stavkeEvidencije);
                ClientController.getInstance().ubaciEvidencijaCasova(evidencija);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio evidenciju casova!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                ec.setProfesor(profesor);
                ec.setUcenik(ucenik);
                ec.setSkolskaGodina(skolskaGodina);
                ec.setDatumPocetka(datumPocetka);
                ec.setDatumZavrsetka(datumZavrsetka);
                ec.setStavke(stavkeEvidencije);
                ClientController.getInstance().promeniEvidencijaCasova(ec);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio evidenciju casova!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            }

            pef.popuniTabelu();
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti evidenciju casova!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        Cas cas = (Cas) jComboBoxCasovi.getSelectedItem();
        String ocenaStr = jTextFieldOcena.getText().trim();
        String napomena = jTextFieldNapomena.getText().trim();
        String datumStr = jTextFieldDatumPrisustva.getText().trim();

        try {
            validirajStavku(cas, ocenaStr, datumStr);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumPrisustva = sdf.parse(datumStr);
            int ocena = Integer.parseInt(ocenaStr);

            StavkaEvidencijeCasova nova = new StavkaEvidencijeCasova();
            nova.setRb((long) stavkeEvidencije.size() + 1);
            nova.setCas(cas);
            nova.setOcena(ocena);
            nova.setDatumPrisustva(datumPrisustva);
            nova.setNapomena(napomena);

            stavkeEvidencije.add(nova);
            popuniTabeluStavki();

            jComboBoxCasovi.setSelectedIndex(-1);
            jTextFieldOcena.setText("");
            jTextFieldNapomena.setText("");
            jTextFieldDatumPrisustva.setText("dd.MM.yyyy");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da doda stavku!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    private void jButtonObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiStavkuActionPerformed
        int red = jTableStavkeEvidencije.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Nijedna stavka nije odabrana!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        stavkeEvidencije.remove(red);
        popuniTabeluStavki();
    }//GEN-LAST:event_jButtonObrisiStavkuActionPerformed

    private void jTextFieldDatumPrisustvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatumPrisustvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDatumPrisustvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<Object> jComboBoxCasovi;
    private javax.swing.JComboBox<Object> jComboBoxProfesor;
    private javax.swing.JComboBox<Object> jComboBoxUcenik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNapomena;
    private javax.swing.JLabel jLabelNapomena1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavkeEvidencije;
    private javax.swing.JTextField jTextFieldBrojPrisustva;
    private javax.swing.JTextField jTextFieldDatumPocetka;
    private javax.swing.JTextField jTextFieldDatumPrisustva;
    private javax.swing.JTextField jTextFieldDatumZavrsetka;
    private javax.swing.JTextField jTextFieldNapomena;
    private javax.swing.JTextField jTextFieldOcena;
    private javax.swing.JTextField jTextFieldProsecnaOcena;
    private javax.swing.JTextField jTextFieldSkolskaGodina;
    private javax.swing.JTextField jTextFieldTrajanjeEvidencije;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            // profesor je uvek ulogovani - ne moze da se menja
            jComboBoxProfesor.removeAllItems();
            jComboBoxProfesor.addItem(ClientController.getInstance().getUlogovani());
            jComboBoxProfesor.setSelectedItem(ClientController.getInstance().getUlogovani());
            jComboBoxProfesor.setEnabled(false);

            jComboBoxUcenik.removeAllItems();
            List<Ucenik> ucenici = ClientController.getInstance().vratiListuSviUcenik();
            for (Ucenik u : ucenici) {
                jComboBoxUcenik.addItem(u);
            }
            jComboBoxUcenik.setSelectedIndex(-1);

            jComboBoxCasovi.removeAllItems();
            List<Cas> casovi = ClientController.getInstance().vratiListuSviCas();
            for (Cas c : casovi) {
                jComboBoxCasovi.addItem(c);
            }
            jComboBoxCasovi.setSelectedIndex(-1);

            // calculated polja - non-editable
            jTextFieldBrojPrisustva.setEnabled(false);
            jTextFieldTrajanjeEvidencije.setEnabled(false);
            jTextFieldProsecnaOcena.setEnabled(false);

            popuniTabeluStavki();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popuniPolja() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        jComboBoxProfesor.setSelectedItem(ec.getProfesor());
        jComboBoxUcenik.setSelectedItem(ec.getUcenik());
        jTextFieldSkolskaGodina.setText(ec.getSkolskaGodina());
        jTextFieldDatumPocetka.setText(sdf.format(ec.getDatumPocetka()));
        jTextFieldDatumZavrsetka.setText(sdf.format(ec.getDatumZavrsetka()));

        popuniTabeluStavki();
    }

    private void popuniTabeluStavki() {
        ModelTabeleStavkaEvidencijeCasova mtsec = new ModelTabeleStavkaEvidencijeCasova(stavkeEvidencije);
        jTableStavkeEvidencije.setModel(mtsec);
        osvežiKalkulisanaPolja();
    }

    private void osvežiKalkulisanaPolja() {
        jTextFieldBrojPrisustva.setText(String.valueOf(stavkeEvidencije.size()));

        if (!stavkeEvidencije.isEmpty()) {
            double prosek = stavkeEvidencije.stream()
                    .mapToInt(StavkaEvidencijeCasova::getOcena)
                    .average()
                    .orElse(0.0);
            jTextFieldProsecnaOcena.setText(String.format("%.2f", prosek));
        } else {
            jTextFieldProsecnaOcena.setText("0.0");
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            if (!jTextFieldDatumPocetka.getText().isEmpty() && !jTextFieldDatumZavrsetka.getText().isEmpty()) {
                Date poc = sdf.parse(jTextFieldDatumPocetka.getText());
                Date kraj = sdf.parse(jTextFieldDatumZavrsetka.getText());
                long trajanje = (kraj.getTime() - poc.getTime()) / (1000 * 60 * 60 * 24);
                jTextFieldTrajanjeEvidencije.setText(String.valueOf(trajanje));
            }
        } catch (Exception e) {
            jTextFieldTrajanjeEvidencije.setText("0");
        }
    }

    private void validirajStavku(Cas cas, String ocenaStr, String datumStr) throws Exception {
        String error = "";

        if (cas == null) {
            error += "Cas mora biti izabran!\n";
        }
        if (ocenaStr.isEmpty()) {
            error += "Ocena ne sme biti prazna!\n";
        } else {
            try {
                int ocena = Integer.parseInt(ocenaStr);
                if (ocena < 1 || ocena > 5) {
                    error += "Ocena mora biti izmedju 1 i 5!\n";
                }
            } catch (NumberFormatException e) {
                error += "Ocena mora biti ceo broj!\n";
            }
        }
        if (datumStr.isEmpty() || datumStr.equals("dd.MM.yyyy")) {
            error += "Datum prisustva ne sme biti prazan!\n";
        } else {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
                Date datumPrisustva = sdf.parse(datumStr);

                String pocStr = jTextFieldDatumPocetka.getText().trim();
                String krajStr = jTextFieldDatumZavrsetka.getText().trim();

                if (!pocStr.isEmpty() && !krajStr.isEmpty()
                        && !pocStr.equals("dd.MM.yyyy") && !krajStr.equals("dd.MM.yyyy")) {
                    Date poc = sdf.parse(pocStr);
                    Date kraj = sdf.parse(krajStr);

                    if (datumPrisustva.before(poc) || datumPrisustva.after(kraj)) {
                        error += "Datum prisustva mora biti izmedju datuma pocetka i zavrsetka evidencije!\n";
                    }
                }
            } catch (Exception e) {
                error += "Datum prisustva nije ispravnog formata! Koristite dd.MM.yyyy\n";
            }
        }

        if (!error.isEmpty()) {
            throw new Exception(error);
        }
    }

    private void validirajEvidenciju(Profesor profesor, Ucenik ucenik, String skolskaGodina,
            String datumPocetkaStr, String datumZavrsetkaStr) throws Exception {
        String error = "";

        if (profesor == null) {
            error += "Profesor mora biti izabran!\n";
        }
        if (ucenik == null) {
            error += "Ucenik mora biti izabran!\n";
        }
        if (skolskaGodina.isEmpty()) {
            error += "Skolska godina ne sme biti prazna!\n";
        } else if (!skolskaGodina.matches(".*/.+")) {
            error += "Skolska godina mora biti u formatu 'xxxx/xxxx'!\n";
        }
        if (datumPocetkaStr.isEmpty()) {
            error += "Datum pocetka ne sme biti prazan!\n";
        }
        if (datumZavrsetkaStr.isEmpty()) {
            error += "Datum zavrsetka ne sme biti prazan!\n";
        }
        if (stavkeEvidencije.isEmpty()) {
            error += "Evidencija mora imati bar jednu stavku!\n";
        }

        if (!error.isEmpty()) {
            throw new Exception(error);
        }

        // provera datuma i skolske godine
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date poc = sdf.parse(datumPocetkaStr);
            Date kraj = sdf.parse(datumZavrsetkaStr);

            if (kraj.before(poc)) {
                throw new Exception("Datum zavrsetka mora biti nakon datuma pocetka!\n");
            }

            if (skolskaGodina.matches("\\d{4}/\\d{4}")) {
                int godinaOd = Integer.parseInt(skolskaGodina.split("/")[0]);
                int godinaDo = Integer.parseInt(skolskaGodina.split("/")[1]);

                Calendar cal = Calendar.getInstance();

                cal.setTime(poc);
                if (cal.get(Calendar.YEAR) != godinaOd) {
                    throw new Exception("Godina datuma pocetka mora biti jednaka prvoj godini skolske godine!\n");
                }

                cal.setTime(kraj);
                if (cal.get(Calendar.YEAR) != godinaDo) {
                    throw new Exception("Godina datuma zavrsetka mora biti jednaka drugoj godini skolske godine!\n");
                }
            }
        } catch (java.text.ParseException e) {
            throw new Exception("Datum nije ispravnog formata! Koristite dd.MM.yyyy\n");
        }
    }

}
