/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import niti.Server;

/**
 *
 * @author Una
 */
public class ServerskaForma extends javax.swing.JFrame {

	private Server server;

	/**
	 * Creates new form ServerskaForma
	 */
	public ServerskaForma() {
		initComponents();
		server = new Server();
		jButtonZaustaviServer.setEnabled(false);
		jLabelStatus.setText("ZAUSTAVLJEN"); // ← dodaj ovo
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButtonPokreniServer = new javax.swing.JButton();
		jButtonZaustaviServer = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabelStatus = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jButtonPokreniServer.setText("POKRENI SERVER");
		jButtonPokreniServer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonPokreniServerActionPerformed(evt);
			}
		});

		jButtonZaustaviServer.setText("ZAUSTAVI SERVER");
		jButtonZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonZaustaviServerActionPerformed(evt);
			}
		});

		jLabel1.setText("Status:");

		jMenu1.setText("KONFIGURACIJA");

		jMenuItem1.setText("baza");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("port");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuBar1.add(jMenu1);
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);
		jMenuBar1.add(jMenu1);

		jMenu2.setText("JSON");

		jMenuItemIzvoz = new javax.swing.JMenuItem();
		jMenuItemIzvoz.setText("Izvezi casove u JSON");
		jMenuItemIzvoz.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemIzvozActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItemIzvoz);

		jMenuItemUvoz = new javax.swing.JMenuItem();
		jMenuItemUvoz.setText("Uvezi casove iz JSON");
		jMenuItemUvoz.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItemUvozActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItemUvoz);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(66, 66, 66).addComponent(jButtonPokreniServer)
						.addGap(41, 41, 41).addComponent(jButtonZaustaviServer).addContainerGap(61, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(41, 41, 41).addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE,
										105, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(85, 85, 85)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(79, 79, 79)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(40, 40, 40)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButtonPokreniServer).addComponent(jButtonZaustaviServer))
				.addContainerGap(119, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPokreniServerActionPerformed

		server.start();
		jLabelStatus.setText("POKRENUT");
		jButtonZaustaviServer.setEnabled(true);
		jButtonPokreniServer.setEnabled(false);
	}// GEN-LAST:event_jButtonPokreniServerActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		FormaKonfBaze baza = new FormaKonfBaze(this, false);
		baza.setVisible(true);
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
		FormaKonfPorta port = new FormaKonfPorta(this, false);
		port.setVisible(true);
	}// GEN-LAST:event_jMenuItem2ActionPerformed

	private void jButtonZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonZaustaviServerActionPerformed
		server.zaustaviServer();
		jLabelStatus.setText("ZAUSTAVLJEN");
		jButtonZaustaviServer.setEnabled(false);
		jButtonPokreniServer.setEnabled(true);
	}// GEN-LAST:event_jButtonZaustaviServerActionPerformed

	private void jMenuItemIzvozActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
            chooser.setDialogTitle("Sacuvaj casove u JSON fajl");
            if (chooser.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
                String putanja = chooser.getSelectedFile().getAbsolutePath();
                if (!putanja.endsWith(".json")) {
                    putanja += ".json";
                }
                so.cas.EksportujCasoveUJsonSO operacija = new so.cas.EksportujCasoveUJsonSO(putanja);
                operacija.izvrsi(new domen.Cas());
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Casovi su uspesno izvezeni u JSON fajl!",
                        "Izvoz", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Greska pri izvozu: " + ex.getMessage(),
                    "Greska", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

	private void jMenuItemUvozActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
            chooser.setDialogTitle("Izaberi JSON fajl sa casovima");
            if (chooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
                String putanja = chooser.getSelectedFile().getAbsolutePath();
                so.cas.UveziCasoveIzJsonSO operacija = new so.cas.UveziCasoveIzJsonSO(putanja);
                operacija.izvrsi(new domen.Cas());

                java.util.List<domen.Cas> casovi = operacija.getCasovi();

                StringBuilder sb = new StringBuilder();
                sb.append("Ucitano ").append(casovi.size()).append(" casova:\n\n");
                for (domen.Cas c : casovi) {
                    sb.append("- ").append(c.getNaziv())
                      .append(" (").append(c.getStilPlesa()).append(", ")
                      .append(c.getTrajanje()).append(" min)\n");
                }

                javax.swing.JTextArea textArea = new javax.swing.JTextArea(sb.toString());
                textArea.setEditable(false);
                javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
                scrollPane.setPreferredSize(new java.awt.Dimension(300, 250));

                javax.swing.JOptionPane.showMessageDialog(this,
                        scrollPane,
                        "Ucitani casovi iz JSON-a",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Greska pri uvozu: " + ex.getMessage(),
                    "Greska", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new ServerskaForma().setVisible(true));
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonPokreniServer;
	private javax.swing.JButton jButtonZaustaviServer;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelStatus;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItemIzvoz;
	private javax.swing.JMenuItem jMenuItemUvoz;
	// End of variables declaration//GEN-END:variables
}
