<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>rs.ac.bg.fon.ai</groupId>
    <artifactId>plesna-skola</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>klijent</artifactId>
  <name>Klijent</name>
  <dependencies>
        <dependency>
            <groupId>rs.ac.bg.fon.ai</groupId>
            <artifactId>zajednicki</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>